version: "3.1"
services:
  db:
    image: mysql:5.6
    container_name: shopware-5.5-mysql
    working_dir: /application
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - mysql-shopware-5.5-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware5
      - MYSQL_USER=shopware5
      - MYSQL_PASSWORD=shopware5

  webserver:
    image: nginx:alpine
    container_name: shopware-5.5-webserver
    working_dir: /application
    volumes:
      - ../:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    env_file: ../config.php
    container_name: shopware-5.5-php-fpm
    working_dir: /application
    volumes:
      - ../:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/phpdbg/conf.d/99-overrides.ini
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shopware-5.5-phpmyadmin
    ports:
      - "8001:80"
    links:
      - db

  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/application

volumes:
  mysql-shopware-5.5-data:
    external: false